FROM selenium/standalone-chrome
USER root
RUN sudo apt update && sudo apt install -y maven \
       openjdk-8-jdk-headless && \
       sudo apt clean
RUN mkdir /src
ADD pom.xml /src/pom.xml
WORKDIR /src
USER seluser
RUN mvn compile

