#Author: Aditya
@BillingByServiceTypeReports
@RegressionADI
Feature: Billing by service Type report end to end validation

  @BSTFilterFields
  Scenario: Fields validation BST
    Given I navigate to Report of type "Billing by Service Type"
    Then I validate if all fields are displaying and are enabled in Billing by service type
    And I validate if there are errors exist in the list

  @BSTReportFields
  Scenario: Validating filters and fields generated with single group by and its line items BST
    Given I add a new generic flag if it is not already existing "Automation Flag" and "Its lit" and "Customer"
    Given I add a new customer source if it is not already existing
    Given I add a new division if it is not already existing
    When I create customer with pref paper and residential property
    And I add additional properties to customer
    And I create a subscription of type "After Agreement Signed"
    And I sign the agreement for subscription of type After Agreement Signed
    When I navigate to Report of type "Billing by Service Type"
    And I group by "Customer Name"
    And I add all the filters
    When I search for the billing customer
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list

  @BSTPrefPaperAndPropertyType
  Scenario: Prefer Paper and Property Type validation BST
    When I create customer with balance with prefers paper and residential property type
    And I search for customer with pref paper and residential property in "Billing by Service Type"
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    When I edit customer to commercial property and not require paper
    And I search for customer without pref paper and commercial property in "Billing by Service Type"
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list

  @BSTStandAlone
  Scenario: Balance Age validation BST with StandAlone Invoices
    When I validate customer with balance age in "Billing by Service Type"
    And I validate if there are errors exist in the list

  @BSTSoldFilter
  Scenario: Sold filters validation BST
    Given I delete a routing group
    Given I create a new user if it is not already existing "Office Staff"
    When I create customer with pref paper and residential property
    And I create a subscription with Sales Rep assigned "Automation User - Office" and "Fire"
    And I navigate to scheduling tab
    And I add a route
    And I search customer
    And I schedule an service appointment
    And I search customer
    And I complete an appointment
    And I set filter for sold date, scheduler, sale teams, sales reps and service invoice
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list

  @BSTCreditMemo
  Scenario: Credit memo validation is BST
    When I create customer with balance with prefers paper and residential property type
    And I create a credit memo for an existing invoice
    And I search credit memo customer on the BST report
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list

  @BSTStandAloneAndWriteOff
  Scenario: Make payment with Coupon or Credit and validate in BST
    When I create customer with balance with prefers paper and residential property type
    And I validate all the fields in the Coupons or Credit window
    And I validate if amounts are displayed correctly in coupons or credits
    Then I make a coupon or credit payment
    And I search standalone write off customer on the BST report
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list

  @BSTMultiGroupByValidation
  Scenario: Multi Group By filter validation in BBST
    When I create customer with balance with prefers paper and residential property type
    And I set group by and subgroups to Billing Frequency, Customer ID and Invoice
    Then I validate Billing by service type report generated from Billing Frequency, Customer ID and Invoice
    And I validate the fields generated by billing by service type report
    Then I search customer in billing frequency line item
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list

  @BSTAutoPayCCorBothFields
  Scenario: AutoPay validation for CC and CC or ACH is BST
    When I create customer with balance with prefers paper and residential property type
    And I add a CC payment option
    And I add an customer in auto pay with credit card and max limit "400"
    Given I navigate to Report of type "Billing by Service Type"
    And I search customer on the BST report with AutoPay as "CC Auto Pay"
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I search customer on the BST report with AutoPay as "CC or ACH Auto Pay"
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list

  @BSTAutoPayACHorBothFields
  Scenario: AutoPay validation for ACH and CC or ACH is BST
    When I create customer with balance with prefers paper and residential property type
    And I add a ACH payment option
    And I add an customer in auto pay with credit card and max limit "400"
    Given I navigate to Report of type "Billing by Service Type"
    And I search customer on the BST report with AutoPay as "ACH Auto Pay"
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I search customer on the BST report with AutoPay as "CC or ACH Auto Pay"
    Then I validate the fields generated by billing by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing by service type report
    And I validate line item data in Billing by service type report
    And I validate the fields are displayed in individual line items in Billing by Service Type
    And I validate if there are errors exist in the list