#Author: Aditya
@PaymentsByServiceTypeReports
@RegressionADI
Feature: Payments by service Type report end to end validation

  @PSTFilterFields
  Scenario: Fields validation PST
    Given I navigate to Report of type "Payments by Service Type"
    Then I validate if all fields are displaying and are enabled in Payments by service type
    And I validate if there are errors exist in the list

  @PSTReportFields
    Scenario:Validating filters and fields generated with single group by and its line items PST
    Given I add a new generic flag if it is not already existing "Automation Flag" and "Its lit" and "Customer"
    Given I add a new customer source if it is not already existing
    Given I add a new division if it is not already existing
    When I create customer with pref paper and residential property
    And I add additional properties to customer
    And I create a subscription of type "After Agreement Signed"
    And I sign the agreement for subscription of type After Agreement Signed
    And I add a CC payment option
    Then I make payment with credit card on file
    When I navigate to Report of type "Billing by Service Type"
    And I group by "Customer Name"
    And I add all the filters
    When I search for the billing customer
    Then I validate the fields generated by billing or payments by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing or payments by service type report
    And I validate line item data in Billing or Payments by service type report

  @PSTPrefPaperAndPropertyType
  Scenario: Prefer Paper and Property Type validation PST
    When I create customer with balance with prefers paper and residential property type
    And I add a CC payment option
    Then I make payment with credit card on file
    And I search for customer with pref paper and residential property in "Payments by Service Type"
    Then I validate the fields generated by billing or payments by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing or payments by service type report
    And I validate line item data in Billing or Payments by service type report
    When I edit customer to commercial property and not require paper
    And I search for customer without pref paper and commercial property in "Payments by Service Type"
    Then I validate the fields generated by billing or payments by service type report
    Then I validate if the report is linked to the customer card
    And I validate data generated from billing or payments by service type report
    And I validate line item data in Billing or Payments by service type report
    And I validate the fields are displayed in individual line items
    And I validate if there are errors exist in the list